wandb_version: 1

output_dir:
  desc: null
  value: outputs/wic_7B_lomo/output_adamw_hf_lr0.03_bs16_warmup0.1_clipnorm1.0
overwrite_output_dir:
  desc: null
  value: true
do_train:
  desc: null
  value: true
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: IntervalStrategy.EPOCH
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 16
per_device_eval_batch_size:
  desc: null
  value: 16
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.03
weight_decay:
  desc: null
  value: 0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 10
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: SchedulerType.LINEAR
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: outputs/runs/Jul03_18-43-20_ip-172-31-66-198
logging_strategy:
  desc: null
  value: IntervalStrategy.STEPS
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: IntervalStrategy.NO
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: 0
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: outputs
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: acc
greater_is_better:
  desc: null
  value: true
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: []
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    fsdp_min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
deepspeed:
  desc: null
  value: config/ds_config.json
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: OptimizerNames.ADAMW_HF
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: false
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: HubStrategy.EVERY_SAVE
hub_token:
  desc: null
  value: null
hub_private_repo:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: true
include_inputs_for_metrics:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: null
_n_gpu:
  desc: null
  value: 1
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
xpu_backend:
  desc: null
  value: null
sortish_sampler:
  desc: null
  value: false
predict_with_generate:
  desc: null
  value: false
generation_max_length:
  desc: null
  value: null
generation_num_beams:
  desc: null
  value: null
generation_config:
  desc: null
  value: null
tag:
  desc: null
  value: lomo
clip_grad_norm:
  desc: null
  value: 1.0
clip_grad_value:
  desc: null
  value: null
clip_loss_value:
  desc: null
  value: null
warmup:
  desc: null
  value: 0.1
max_length:
  desc: null
  value: 20
max_new_tokens:
  desc: null
  value: null
do_sample:
  desc: null
  value: false
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_normalization:
  desc: null
  value: true
unconditional_normalization:
  desc: null
  value: false
hf_learning_rate:
  desc: null
  value: 0.0005
hf_weight_decay:
  desc: null
  value: 0.0
hf_lr_scheduler_type:
  desc: null
  value: linear
hf_warmup:
  desc: null
  value: 0
peft_type:
  desc: null
  value: null
lora_r:
  desc: null
  value: 8
lora_alpha:
  desc: null
  value: 16
lora_dropout:
  desc: null
  value: 0.05
lora_only:
  desc: null
  value: false
model_name_or_path:
  desc: null
  value: /remote-home/share/llama_hf/7B
cache_dir:
  desc: null
  value: ../llama/checkpoint
data_dir:
  desc: null
  value: data
dataset_name:
  desc: null
  value: wic
refresh:
  desc: null
  value: false
data_tag:
  desc: null
  value: base
prompt_type:
  desc: null
  value: natural
train_on_inputs:
  desc: null
  value: false
data_max_length:
  desc: null
  value: 1024
few_shot_size:
  desc: null
  value: -1
in_context_learning:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.30.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688409800.870251
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.15.4
      6: 4.30.1
      8:
      - 5
